### PR TITLE
Update .travis.yml to build docker image

### PR DESCRIPTION
**Pull request by maxb2**
I separated the travis ci into different stages and added a job to build a docker image. We can use travis for all the tests that pull requests need to pass since ci/dockercloud isn't responding.

### CODE REVIEW

**Comment by maxb2** [comment]
I haven't included it yet, but we could [build and push](https://docs.travis-ci.com/user/build-stages/share-docker-image/) a docker image from travis. We can also [deploy github releases](https://docs.travis-ci.com/user/build-stages/deploy-github-releases/).

**Comment by n1ru4l** [comment]
Huge 👍 for build/push and deploy from travis. How should we handle versioning with travis doing the releases?

**Comment by maxb2** [comment]
I believe you can deploy releases only on tagged commits. I'm still reading about it. Right now, I'm doing all the ci testing on my fork so we don't make this repo messy.

**Comment by maxb2** [comment]
For the deployment to work, you have to generate an OAuth token and save it as `GITHUB_OAUTH_TOKEN` environment variable in travis-ci settings. Currently, travis only deploys on a tagged commit and only makes a release draft. A maintainer has to finalize the draft on the releases page for it to be public. This can easily be disabled if need be.

**Comment by maxb2** [comment]
I need to rewrite this to be more efficient. Closing for now.

**Pull request closed without merging**
