### PR TITLE
Travis zip binary deployment

### LINKED ISSUE #92: macosx executable is not executable by default
I was testing the 1.2.0 draft release when realizing that the macosx executable is not executable by default. It only outputs a mess of code, after doing `chmod +x` everything worked as expected.

@maxb2 Would this be fixable by running `chmod +x` on the CI before uploading?

### PR DESCRIPTION
**Pull request by maxb2**
This deploys the binaries in a zip file so that they keep the executable bit.

Fixes #92.

### CODE REVIEW

**Comment by maxb2** [comment]
After this is merged, we should tag and publish another release.

**Comment by apclary** [comment]
Are you able to do a release? Or can only I?

**Comment by maxb2** [comment]
> Are you able to do a release? Or can only I?

I believe I can. However, I decided to upload the zip generated by my fork to the release draft we already had waiting. Seemed simpler.

**Comment by n1ru4l** [comment]
Can‘t we do one archive per platform?

**Comment by maxb2** [comment]
> Can‘t we do one archive per platform?

See #108

**Pull request merged**
