### PR TITLE
feature: set map grid

### LINKED ISSUE #30: Grid Lines
Grid Lines on both player and dm screen. Looking at implementing this as well.

FYI: I currently use this app for my huge screen that the players play on. 
Also looking into splitting off the map image into a separate channels, only passing the map once. (Either a URL, Video, or Image once)

Leaving the other channel for the FOW, and Grid Lines. (So I can do live updates, with bigger maps)

### LINKED ISSUE #148: dm-area: reduce the amount of used canvases
Currently, there are three canvases which have quite some impact on performance (especially when zooming/dragging).

When removing the cursor & fog canvas from the DOM I notice a significant performance improvement.
I am pretty sure this is caused by the transparency/absolute positioning of the different stacked canvases.

We can definitely move the cursor stuff onto the object SVG. However, I am still unsure about the shadow canvas. Maybe we can merge both the map and shadow canvas.

I am as always open for suggestions 🤔

### PR DESCRIPTION
**Pull request by n1ru4l**
This pull request adds a wizard for defining a grid for a given map. The grid info is persisted with the map settings and can be shown/hidden from the players. (Closes #30)

Also, I reduced the number of stacked canvases by using OffscreenCanvas. This drastically improved the drag/zoom performance of the map. (Closes #148)

The grid info can further be used for e.g. snapping tokens to the grid ~~or snapping the area selection to grid~~ (**Edit:** I already implemented snapping the area selection to the grid). However, those features should be part of follow up pull requests.

**Video of this feature**: https://streamable.com/a7ujs

**TODO:**

- [x] Grid Wizard for setting up Grids for Maps
- [x] Make Grid Wizard a bit prettier
- [x] move mouse cursors to SVG layer (#148)
- [x] show grid to players
- [x] test browser compatibility (add offscreen canvas polyfill)
- [x] snap area selection to grid
- [x] make grid color configurable
- [x] configure sending the grid to players
- [x] Set grid wizard: handle touch events
- [x] Set grid wizard: smaller screens
- [x] Set grid wizard: select single field on low resolution map

### CODE REVIEW

**Comment by n1ru4l** [comment]
@Azkel I hope this does not cause huge conflicts with what you are working on in #35

@apclary @thorgod Let me know what you think!

**Comment by n1ru4l** [comment]
@thorgod I used the red color because it was great for distinguishing it from the background  during development 😂

Do you think there is a use-case for having different grid colors for DM and players? Otherwise, I think the following settings would be beneficial:

- set grid color as rgba (as you mentioned)
- set grid line width
- visibility to players
- visibility for DM

Will play around on how to intuitively integrate this into the UI.

It would also make sense to decouple "snap area-selection to grid" from send grid to players.

**Comment by apclary** [comment]
I'm trying to run this locally but I get a white screen when I click the Dungeon Master link (which, I need to fix because it took me awhile to realize it was there! Poor UX on my part). There are no console entries either.

The terminal console looks like this:
```
GET /map 200 0.379 ms - 55
a user disconnected
GET /map 304 0.327 ms - -
GET /dm 304 0.554 ms - -
a user disconnected
GET /static/css/main.4492e1de.chunk.css 304 0.491 ms - -
GET /static/js/main.c02a5c99.chunk.js 304 0.515 ms - -
GET /static/js/5.1e4d5b95.chunk.js 304 2.964 ms - -
GET /static/js/0.4fb422ec.chunk.js 304 0.767 ms - -
GET /static/js/4.43be4867.chunk.js 304 3.424 ms - -
GET /static/js/1.cf079073.chunk.js 304 0.622 ms - -
GET /static/js/6.046750f1.chunk.js 304 1.693 ms - -
GET /map 304 0.398 ms - -
```

On the other console:
```
[HPM] Error occurred while trying to proxy request /socket.io/?EIO=3&transport=polling&t=MpQtkg5 from localhost:3001 to ws://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /active-map from localhost:3001 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket.io/?EIO=3&transport=polling&t=MpQtl4X from localhost:3001 to ws://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket.io/?EIO=3&transport=polling&t=MpQtm2T from localhost:3001 to ws://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket.io/?EIO=3&transport=polling&t=MpQtn_T from localhost:3001 to ws://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket.io/?EIO=3&transport=polling&t=MpQtpyT from localhost:3001 to ws://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket.io/?EIO=3&transport=polling&t=MpQtrvT from localhost:3001 to ws://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket.io/?EIO=3&transport=polling&t=MpQttsT from localhost:3001 to ws://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Client disconnected
```

Perhaps I messed up the username/password login, I think I cancelled out of it the first time and the second time I tried a blank username and "password" for password, and the third time I tried "dm" for the username and "password" for password.

**Comment by apclary** [comment]
I tried this on MacOS (previously Windows 10) and got the same result. I needed to run `npm install --save-dev acorn` to get npm install to work. And the DM page was just a white screen. To check if there was something I was doing wrong, I pointed back to master branch and when I went to /dm I got a UI and was prompted to pick a map.

**Comment by n1ru4l** [comment]
Have you tried deleting the lockigem (package-lock.json) and removing the node_modules folder, followed by a fresh npm install?

**Comment by n1ru4l** [comment]
@thorgod please check https://github.com/apclary/dungeon-revealer/pull/146/commits/9eb9599ac606f62b3561a5cd58fb4f0e570849e8

**Comment by apclary** [comment]
@n1ru4l That was totally it! D'oh.

**Comment by n1ru4l** [comment]
@apclary I think we should maybe commit the package-lock.json file to git.

**Comment by apclary** [comment]
@n1ru4l Agree

**Comment by thorgod** [comment]
> @thorgod I used the red color because it was great for distinguishing it from the background during development 
> 
> Do you think there is a use-case for having different grid colors for DM and players? Otherwise, I think the following settings would be beneficial:

To me it would be the same both player and DM. I do not see a need to make it different.

**Comment by n1ru4l** [comment]
@apclary what exactly is the issue with low resolution maps? I only testen on 15“ screen

**Comment by apclary** [comment]
@n1ru4l when I used some lower-resolution images, the "select grid" feature did not fully render the grid, maybe only the top 2/3 of it. I had used a pretty small image, maybe it was only 800x600 so not really relevant. That was with a 2014 MBP in Google Chrome.

**Comment by n1ru4l** [comment]
Can you please share the picture?

**Comment by apclary** [comment]
@n1ru4l Sure, here is the image. https://imgur.com/a/HrFiG5F

And this is what I saw: https://imgur.com/K40gQ7R

**Comment by n1ru4l** [comment]
Did a little bit of polishing and also fixed the issue reported in https://github.com/apclary/dungeon-revealer/pull/146#issuecomment-526659747

I am going to merge this now and will release a new version.

**Pull request merged**
