### PR TITLE
feat: add area select tool

### LINKED ISSUE #36: Select area to reveal fog
On Roll20 you can reveal the fog area by selecting an area via click drag release. 

This would be an useful addition for revealing huge quadratic shapes without having to click the increase brush size button for ages.

In addition to that, this feature would improve the usability on tablets where you do not have a cursor and therefore cannot exactly say how large the revealed area from the brush will be.

I will work on this feature.

### PR DESCRIPTION
**Pull request by n1ru4l**
This pull request adds a new tool `Select Area`. The DM can now switch between the `Select Area` and the `Brush` tool.

The new tool allows the dm to select a square area that he wants to reveal or shroud.

Closes #36

# Preview

I created a preview gif

output

### CODE REVIEW

**Comment by thorgod** [comment]
That is really cool!

**Comment by apclary** [comment]
Impressive! Would maybe be good to add gifs to our readme.

**Comment by n1ru4l** [comment]
@apclary That would be a nice idea. I will experiment a bit because currently, the file size of the gif is pretty huge. 

I will merge this pull request for now.

**Comment by maxb2** [comment]
Should we make a tag on master so that we have this feature included in a binary release?

**Pull request merged**
