### PR TITLE
Rename npm run scripts

### PR DESCRIPTION
**Pull request by Quintasan**
`npm run start` doesn't sound like running backend nor does `npm run
start:dev` suggest running frontend.

### CODE REVIEW

**Comment by n1ru4l** [comment]
`npm start` is an alias for `npm run start` and the default goto command for starting a node.js application with a `package.json`.

`npm run start:dev` is only required during development (for the react dev server).

I do not think that making the commands you have to type longer brings any value. The contribution guide already contains all the necessary info.

@Quintasan am going to close this for now. If there is anything I am missing feel free to explain further.

**Comment by Quintasan** [comment]
Well, at the very least, fix the `npm run install` command since it's not
going to work on any PC as far as I know.

czw., 29 sie 2019, 16:39 użytkownik Laurin Quast <notifications@github.com>
napisał:

**Comment by n1ru4l** [comment]
@apclary did address this yesterday: https://github.com/apclary/dungeon-revealer/commit/abe8cd7398842c17d02eb02298fec449a855ce69

**Comment by Quintasan** [comment]
Oh, great!

czw., 29 sie 2019, 17:52 użytkownik Laurin Quast <notifications@github.com>
napisał:

**Pull request closed without merging**
