### PR TITLE
Add Docker 

### PR DESCRIPTION
**Pull request by maxb2**
I've added a Dockerfile to create an image out of this app using the instructions from [here](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/). 

It is also possible to set up a Docker Hub repo to [follow a github repository](https://docs.docker.com/docker-hub/builds/link-source/). 

I updated the README to include instructions to run the docker container. Feel free to set up your own hub repo and point to it instead of mine.

### CODE REVIEW

**Comment by apclary** [comment]
The readme will say `docker run -e DM_PASSWORD=<password> -p <PORT>:3000 -d maxb2/dungeon-revealer`, can you change it to say apclary so its pointing to the right repo? Maybe there is a way to inject the repo name into markdown.

**Comment by maxb2** [comment]
I believe you can edit the pull request since you are a maintainer. If not, I'll submit a new one. You do have to set up a docker hub repo to track the github repo though.

**Comment by apclary** [comment]
OK I merged your change and updated the README in a separate commit (through the web UI). I set up and linked docker hub to this repo, but if someone wants to test if it works or what else I need to do, feel free to do it or let me know what else I need to do.

https://hub.docker.com/r/apclary/dungeon-revealer

**Comment by maxb2** [comment]
It's working for me.

**Pull request merged**
