### PR TITLE
travis: add docker dev deployment

### LINKED ISSUE #59: Change dockercloud CI tag
I would suggest changing the dockercloud ci tag to `dev` instead of `latest`. This is because we tend to implement small changes in master here on github without necessarily incrementing the version number and issuing a release. I think the `latest` tag on docker should be reserved for tagged releases here on github. The travis build from #56 will build the images associated with a github release/tag and push them to dockercloud with both the `latest` tag and a version tag.

### PR DESCRIPTION
**Pull request by maxb2**
This adds a docker deployment with the `dev` tag for commits on the master branch. We can turn off all builds on dockerhub if we use this.

Resolves #59.

### CODE REVIEW

**Comment by maxb2** [comment]
@apclary, if you could remove all the builds and checks on dockerhub, that would finalize this.

**Comment by maxb2** [comment]
@apclary, I just noticed that dockerhub built the latest commit to master and tagged it with `latest`. That shouldn't be happening. Only github tagged releases should use that docker tag. I've found that dockerhub's CI is hard to configure correctly. We should really turn off all dockerhub CI in favor of the travis configuration in this pull request.

**Comment by apclary** [comment]
@maxb2 To confirm, you want me to make no dockerhub changes and merge this PR as-is?

**Comment by maxb2** [comment]
@apclary, not quite. Turn all the builds and checks on dockerhub off. Travis will take care of everything.

**Comment by apclary** [comment]
Ok I merged this and turned off all dockerhub builds.

**Pull request merged**
