### PR TITLE
feat: multiple maps

### LINKED ISSUE #15: Suggestion - Multiple maps
Hi apclary !

First, thank you so much for this tool ! It is really simple and efficient, and fits exactly my needs as a DM !

Here is a suggestion to make the tool even more cool. Could you add multiple maps support ? For dungeons with multiple levels, for example, it would be awesome if the DM could switch back and forth between maps, saving the currently cleared area of the maps.

### LINKED ISSUE #54: Improve Send Performance
I noticed that the more of a map is revealed the longer the sending/receiving aka time to send until the player sees the updates increases drastically.  This might be because sending a black image is faster than sending the actual map.

Maybe it would be possible to send the actual map initially and only send the updated fog image after updates. This would allow users to see the whole map (not just the revealed parts) if they use the developer tools to inspect the DOM or trace the HTTP requests. However, since this tool is intended for home use I do not think cheating would be an issue.

Do you have any other optimizations in mind? Detecting affected areas (that the dm draws on) and sending only those could be a more complicated but also effective change.

### LINKED ISSUE #60: Uploading a new map doesn't always work
Trying to upload a new map doesn't always work. After clicking new map and uploading a file, the previous map is still loaded in the page. After refreshing the page you can successfully upload a new map once and then it is broken again. I saw this behavior in both firefox and chromium.

Log:
```
> dungeon-revealer@1.0.0 start /usr/src/app
> node ./bin/dungeon-revealer

Listening at http://localhost:3000
Point your browser to that address
Have your players point their browsers to http://[REDACTED]:3000
Thu, 09 May 2019 20:52:28 GMT express deprecated res.sendfile: Use res.sendFile instead at app.js:155:7
GET / 200 7.509 ms - 2932
GET /stylesheets/bootstrap.min.css 200 1.944 ms - 117024
GET /static/js/main.48fe2250.chunk.js 200 1.401 ms - 904
GET /static/css/main.9aace31b.chunk.css 200 1.816 ms - 2543
GET /static/js/3.b716f758.chunk.js 200 1.707 ms - 125421
GET /static/js/2.0131b56b.chunk.js 200 0.423 ms - 110966
GET /static/js/5.1e0501b5.chunk.js 200 0.625 ms - 2399
GET /favicon.ico 200 1.445 ms - 34494
GET /fonts/folkard.woff 200 0.514 ms - 18464
GET /images/DungeonEntranceMedium.jpg 200 0.577 ms - 3788500
a user connected
```
Connect as the DM
```
a user disconnected
Thu, 09 May 2019 20:53:11 GMT express deprecated res.sendfile: Use res.sendFile instead at app.js:159:7
GET /dm 200 1.177 ms - 2932
GET /stylesheets/bootstrap.min.css 304 0.842 ms - -
GET /static/css/main.9aace31b.chunk.css 304 0.715 ms - -
GET /static/js/3.b716f758.chunk.js 304 0.635 ms - -
GET /static/js/main.48fe2250.chunk.js 304 0.618 ms - -
GET /static/js/4.7ea716b6.chunk.js 200 0.435 ms - 12848
GET /dm/map 401 1.048 ms - 0
Uploading image to /usr/src/uploads/
GET /dm/map 404 1.630 ms - 9
```
Upload first map
```
map uploaded
POST /upload 200 4.577 ms - 2
GET /dm/map 200 0.635 ms - 7859
```
Upload 2nd map (still shows previous map)
```
Deleting old map /usr/src/uploads/map.png
map uploaded
POST /upload 200 6.293 ms - 2
```
Refresh site (first map still on screen)
```
GET /dm 304 0.562 ms - -
GET /stylesheets/bootstrap.min.css 304 0.545 ms - -
GET /static/css/main.9aace31b.chunk.css 304 0.613 ms - -
GET /static/js/3.b716f758.chunk.js 304 0.610 ms - -
GET /static/js/main.48fe2250.chunk.js 304 0.619 ms - -
GET /static/js/4.7ea716b6.chunk.js 304 0.217 ms - -
GET /dm/map 200 0.490 ms - 10362
GET /dm/map 304 0.299 ms - -
```
Upload 3rd map (replaces map as expected)
```
Deleting old map /usr/src/uploads/map.png
map uploaded
POST /upload 200 77.631 ms - 2
GET /dm/map 200 0.669 ms - 15212424
```
Upload 4th map (3rd map still on screen)
```
Deleting old map /usr/src/uploads/map.png
map uploaded
POST /upload 200 3.066 ms - 2
```
It looks like when you upload a map, it doesn't always `GET /dm/map`.

### PR DESCRIPTION
**Pull request by n1ru4l**
Closes #15
Closes #54
Closes #60

- [x] Store fog progress as png on the backend
- [x] UI for creating and browsing multiple maps

### CODE REVIEW

**Comment by apclary** [comment]
I'm surprised it says waiting on travis. Did I configure something wrong?

**Comment by maxb2** [comment]
> I'm surprised it says waiting on travis. Did I configure something wrong?

I believe travis only builds pull requests that have been marked ready for review. I think the dockercloud ci is broken and just looks at the latest build status. We should remove the dockercloud ci since travis builds the docker image and pushes to dockercloud.

**Comment by maxb2** [comment]
The [details link](https://cloud.docker.com/redirect/?resource_uri=/api/audit/v1/action/155a233e-0247-43f7-aeb3-d5ba06e9e6fd/) below for the dockercloud ci is giving me a 500 error. @apclary, are you seeing the same thing? Is it a repository permissions issue?

**Comment by apclary** [comment]
@maxb2 that links shows a successful build of the multimap feature for me

**Comment by maxb2** [comment]
Ok, I think it links somewhere only you can see and gives me a 500 because of that. I'm able to get [here](https://cloud.docker.com/repository/registry-1.docker.io/apclary/dungeon-revealer) in your repo, but it won't let me click on anything. It's good to know the builds are working though.

**Comment by n1ru4l** [comment]
Okay, it is now useable! @apclary, @maxb2, and @thorgod it would be awesome if you could test everything and confirm everything works as it should

Currently there a few limitations that I did not reimplement yet:

1. Fade in the new fog
2. Drag And Drop Upload

We could either reimplement them in a further pull request or I can continue my work here before merging.

**Comment by maxb2** [comment]
I'm looking into why the travis build failed. It might be the node cache.

**Comment by n1ru4l** [comment]
@maxb2 It is eslint warnings :P

**Comment by apclary** [comment]
I got this error trying to run npm install on windows:
```

$ npm install
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

> husky@2.1.0 install C:\Users\apcla\Documents\GitHub\dungeon-revealer-multi-map\node_modules\husky
> node husky install

husky > setting up git hooks
husky > done
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\apcla\Documents\GitHub\dungeon-revealer-multi-map\node_modules\jest-haste-map\node_modules\fsevents\node_modules'

> dungeon-revealer@1.0.0 postinstall C:\Users\apcla\Documents\GitHub\dungeon-revealer-multi-map
> npm run build


> dungeon-revealer@1.0.0 build C:\Users\apcla\Documents\GitHub\dungeon-revealer-multi-map
> react-scripts build && ./node_modules/.bin/pkg . --out-path ./bin/ --targets node10-win-x64,node10-macos-x64,node10-linux-x64

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'acorn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\apcla\Documents\GitHub\dungeon-revealer-multi-map\node_modules\acorn-dynamic-import\lib\index.js:18:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dungeon-revealer@1.0.0 build: `react-scripts build && ./node_modules/.bin/pkg . --out-path ./bin/ --targets node10-win-x64,node10-macos-x64,node10-linux-x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dungeon-revealer@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\apcla\AppData\Roaming\npm-cache\_logs\2019-05-10T16_04_34_457Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dungeon-revealer@1.0.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dungeon-revealer@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\apcla\AppData\Roaming\npm-cache\_logs\2019-05-10T16_04_34_500Z-debug.log

```

**Comment by maxb2** [comment]
This is looking great! It also solves #60.

**Comment by maxb2** [comment]
It works with `npm run start` on linux. However, the executable is trying to make a directory in a very bad place.
```
pkg/prelude/bootstrap.js:1183
      throw error;
      ^

Error: EACCES: permission denied, mkdir '/snapshot'
    at Object.fs.mkdirSync (fs.js:874:3)
    at mkdirsSync (/snapshot/dungeon-revealer/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at mkdirsSync (/snapshot/dungeon-revealer/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:36:14)
    at mkdirsSync (/snapshot/dungeon-revealer/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:37:7)
    at mkdirsSync (/snapshot/dungeon-revealer/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:37:7)
    at mkdirsSync (/snapshot/dungeon-revealer/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:37:7)
    at mkdirsSync (/snapshot/dungeon-revealer/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:37:7)
    at mkdirsSync (/snapshot/dungeon-revealer/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:37:7)
    at mkdirsSync (/snapshot/dungeon-revealer/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:37:7)
    at mkdirsSync (/snapshot/dungeon-revealer/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:37:7)
```

**Comment by apclary** [comment]
It's the post build that's failing, in windows, looks like. Not sure if it fails in linux. If I run `npm install` and then ignore the post build error, I can run `npm start` and the server starts.

I tried running` npm install --save acorn` to see if that might resolve the error and it did get me past that error, but there was a new error later on:

```
> react-scripts build && ./node_modules/.bin/pkg . --out-path ./bin/ --targets node10-win-x64,node10-macos-x64,node10-linux-x64

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  38.51 KB  build\static\js\4.0c366430.chunk.js
  28.96 KB  build\static\js\2.258d6946.chunk.js
  8.25 KB   build\static\js\3.e5efceab.chunk.js
  1.23 KB   build\static\js\5.eae792da.chunk.js
  1.15 KB   build\static\js\runtime~main.eb039e81.js
  927 B     build\static\css\main.60f95d95.chunk.css
  536 B     build\static\js\main.bfcd59e1.chunk.js

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://bit.ly/CRA-deploy

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dungeon-revealer@1.0.0 build: `react-scripts build && ./node_modules/.bin/pkg . --out-path ./bin/ --targets node10-win-x64,node10-macos-x64,node10-linux-x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dungeon-revealer@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\apcla\AppData\Roaming\npm-cache\_logs\2019-05-10T16_13_35_790Z-debug.log

```

One thing I did notice, and this may be totally unrelated, was that I got spammed with hundreds of "a user disconnected" messages.

**Comment by maxb2** [comment]
Maybe we should use a [temp directory](https://stackoverflow.com/a/37077780) to store things on the disk since the executables keep trying to make directories.

**Comment by n1ru4l** [comment]
@maxb2 check ac9e6c8

**Comment by n1ru4l** [comment]
any crooss-platform solutions for `./node_modules/.bin/pkg .`? Seems like windows does not like that 😅

**Comment by maxb2** [comment]
Linux is working great.

**Comment by n1ru4l** [comment]
@apclary does c3ce373 resolve your issue?

**Comment by apclary** [comment]
@n1ru4l No, prior to that it would work in Windows (Bash and powershell) if you ran `react-scripts build` and `./node_modules/.bin/pkg package.json --out-path ./bin/ --targets node10-win-x64,node10-macos-x64,node10-linux-x64` separately. It's only when run as a single command that it fails.

It appears to be the relative reference to `pkg` that causes the problem. If I change the line to this:

`"build": "react-scripts build && pkg . --out-path ./bin/ --targets node10-win-x64,node10-macos-x64,node10-linux-x64",`

it works.

**Comment by n1ru4l** [comment]
I have no windows machine. I did not run in the acorn issue. On CI we are also not experiencing this issue 😕. I do not think that excluding windows from development is the correct move. node is meant to be cross-platform.

**Comment by apclary** [comment]
That's possible, I did notice acorn in the package-lock.json file. I will merge this.

**Comment by maxb2** [comment]
We should tag and release this.

**Comment by n1ru4l** [comment]
@maxb2 create v.1.1.0 tag, currently, it is building : https://travis-ci.org/apclary/dungeon-revealer/builds/530903432

**Comment by n1ru4l** [comment]
@maxb2 it failed to publish the assets to github, could you please take a look on it?

**Comment by maxb2** [comment]
@apclary has to generate an oauth token for travis to be able to write to the repository. See #56 for links and instructions.

**Comment by apclary** [comment]
I'll see if I can get it to work

**Comment by apclary** [comment]
OK I added the DOCKER_PASSWORD, DOCKER_USERNAME, and GITHUB_OATH_TOKEN environment variables in Travis.

**Comment by n1ru4l** [comment]
@maxb2 how do we retrigger the build?

**Comment by maxb2** [comment]
@apclary you misspelled oauth in the environment variable on the settings page. We're nearly there.

**Comment by maxb2** [comment]
@n1ru4l if you go to the build page, there is a restart job/build button on the right.

**Comment by apclary** [comment]
I fixed the naming

**Comment by n1ru4l** [comment]
I think I do not have permissions to retrigger the build

**Comment by maxb2** [comment]
I think you have to be logged in with your github account first.

**Comment by maxb2** [comment]
The github deployment worked. The dockerhub deployment says the username and password are incorrect though.

**Comment by apclary** [comment]
I used my email which was my username saved in Chrome, but I'll try just "apclary" and see if that fixes it.

**Pull request merged**
